In [2]:
import pandas as pd
df= pd.read_csv("EURUSD5_data.csv")

In [15]:
df[['datadate','tic','adjcp','adjcp','high','low','volume']]

           datadate      tic    adjcp    adjcp     high      low  volume
0      202309010000  EURUSD5  1.08422  1.08422  1.08422  1.08424     535
1      202309010005  EURUSD5  1.08424  1.08424  1.08410  1.08418     403
2      202309010010  EURUSD5  1.08417  1.08417  1.08403  1.08405     508
3      202309010015  EURUSD5  1.08404  1.08404  1.08378  1.08386     502
4      202309010020  EURUSD5  1.08385  1.08385  1.08381  1.08401     256
...             ...      ...      ...      ...      ...      ...     ...
18930  202312012135  EURUSD5  1.08801  1.08801  1.08780  1.08781     475
18931  202312012140  EURUSD5  1.08781  1.08781  1.08780  1.08799     337
18932  202312012145  EURUSD5  1.08798  1.08798  1.08787  1.08790     338
18933  202312012150  EURUSD5  1.08791  1.08791  1.08785  1.08810     641
18934  202312012155  EURUSD5  1.08812  1.08812  1.08786  1.08788    1262

[18935 rows x 7 columns]