In [14]:
import pandas as pd
data=pd.read_csv('predict_eval_m5.csv')
# Splitting the 'Ticket' column into two parts
data['Ticket Code'] = data['Ticket'].str.extract(r'([A-Za-z]+)')
data['Period Time'] = data['Ticket'].str.extract(r'(\d+)')

# Convert 'Period Time' to integer
data['Period Time'] = data['Period Time'].astype(int)

# Display the updated dataframe
# Removing the numeric part (1440) from the 'Ticket' column
data['Ticket'] = data['Ticket Code']
data['MSE m5'] = data['MSE']
data['RMSE m5'] = data['RMSE']
data['MAPE m5'] = data['MAPE']

# # Sorting the dataframe by 'Ticket' and then by 'Model'
data= data[['Ticket', 'Model', 'MSE m5','RMSE m5', 'MAPE m5' ]]
sorted_data1 = data.sort_values(by=['Ticket', 'Model'])
# # Display the sorted dataframe
sorted_data1.head()

   Ticket      Model  MSE m5  RMSE m5  MAPE m5
2  EURUSD   A2C(GRU)  0.7900   0.0265   1.3738
0  EURUSD  A2C(LSTM)  0.8032   0.4673   0.2000
5  EURUSD   DQN(GRU)  1.6459   0.6393   0.1999
1  EURUSD  DQN(LSTM)  1.6684   0.0745   0.7722
4  EURUSD   PPO(GRU)  1.0300   0.4464   0.3132

In [8]:
data

    Ticket      Model  MSE m5  RMSE m5  MAPE m5
0   EURUSD  A2C(LSTM)  0.8032   0.4673   0.2000
1   EURUSD  DQN(LSTM)  1.6684   0.0745   0.7722
2   EURUSD   A2C(GRU)  0.7900   0.0265   1.3738
3   EURUSD  PPO(LSTM)  2.1303   0.0650   1.8577
4   EURUSD   PPO(GRU)  1.0300   0.4464   0.3132
5   EURUSD   DQN(GRU)  1.6459   0.6393   0.1999
6   GBPUSD  A2C(LSTM)  1.9161   0.4882   0.3005
7   GBPUSD  DQN(LSTM)  1.6747   0.9748   1.0749
8   GBPUSD   A2C(GRU)  2.1780   1.6370   1.4175
9   GBPUSD  PPO(LSTM)  0.5265   1.4302   0.7262
10  GBPUSD   PPO(GRU)  0.9585   1.0271   0.3954
11  GBPUSD   DQN(GRU)  0.5210   0.5979   0.1257
12  USDCAD  A2C(LSTM)  1.9721   0.2306   0.6233
13  USDCAD  DQN(LSTM)  1.9932   0.0759   0.3231
14  USDCAD   A2C(GRU)  0.2603   1.2020   0.9429
15  USDCAD  PPO(LSTM)  1.6769   1.1604   0.8418
16  USDCAD   PPO(GRU)  0.4764   0.2652   0.5806
17  USDCAD   DQN(GRU)  0.4092   0.8271   0.5032

In [16]:
import pandas as pd
data=pd.read_csv('predict_eval_h1.csv')
# Splitting the 'Ticket' column into two parts
data['Ticket Code'] = data['Ticket'].str.extract(r'([A-Za-z]+)')
data['Period Time'] = data['Ticket'].str.extract(r'(\d+)')

# Convert 'Period Time' to integer
data['Period Time'] = data['Period Time'].astype(int)

# Display the updated dataframe
# Removing the numeric part (1440) from the 'Ticket' column
data['Ticket'] = data['Ticket Code']
data['MSE H1'] = data['MSE']
data['RMSE H1'] = data['RMSE']
data['MAPE H1'] = data['MAPE']

# # Sorting the dataframe by 'Ticket' and then by 'Model'
data= data[['Ticket', 'Model', 'MSE H1','RMSE H1', 'MAPE H1' ]]
sorted_data2 = data.sort_values(by=['Ticket', 'Model'])
# # Display the sorted dataframe
sorted_data2.head()

   Ticket      Model  MSE H1  RMSE H1  MAPE H1
2  EURUSD   A2C(GRU)  2.0279   0.5072   0.0900
0  EURUSD  A2C(LSTM)  0.8320   0.0234   0.7492
5  EURUSD   DQN(GRU)  0.5529   0.7506   0.3341
1  EURUSD  DQN(LSTM)  1.4546   0.7357   0.0724
4  EURUSD   PPO(GRU)  0.4705   0.0497   0.6718

In [17]:
import pandas as pd
data=pd.read_csv('predict_eval_d1.csv')
# Splitting the 'Ticket' column into two parts
data['Ticket Code'] = data['Ticket'].str.extract(r'([A-Za-z]+)')
data['Period Time'] = data['Ticket'].str.extract(r'(\d+)')

# Convert 'Period Time' to integer
data['Period Time'] = data['Period Time'].astype(int)

# Display the updated dataframe
# Removing the numeric part (1440) from the 'Ticket' column
data['Ticket'] = data['Ticket Code']
data['MSE D1'] = data['MSE']
data['RMSE D1'] = data['RMSE']
data['MAPE D1'] = data['MAPE']

# # Sorting the dataframe by 'Ticket' and then by 'Model'
data= data[['Ticket', 'Model', 'MSE D1','RMSE D1', 'MAPE D1' ]]
sorted_data3 = data.sort_values(by=['Ticket', 'Model'])
# # Display the sorted dataframe
sorted_data3.head()

   Ticket      Model  MSE D1  RMSE D1  MAPE D1
2  EURUSD   A2C(GRU)  2.3167   1.0330   0.3265
0  EURUSD  A2C(LSTM)  1.5868   0.1293   0.1676
5  EURUSD   DQN(GRU)  0.1706   0.7323   0.7832
1  EURUSD  DQN(LSTM)  0.4106   0.9303   0.7827
4  EURUSD   PPO(GRU)  1.7862   0.7682   0.7357

In [18]:
data=sorted_data1

In [20]:
data['MSE H1'] = sorted_data2['MSE H1']
data['RMSE H1'] = sorted_data2['RMSE H1']
data['MAPE H1'] = sorted_data2['MAPE H1']
data['MSE D1'] = sorted_data3['MSE D1']
data['RMSE D1'] = sorted_data3['RMSE D1']
data['MAPE D1'] = sorted_data3['MAPE D1']

In [21]:
data

,Ticket,Model,MSE m5,RMSE m5,MAPE m5,MSE H1,RMSE H1,MAPE H1,MSE D1,RMSE D1,MAPE D1
2,EURUSD,A2C(GRU),0.7900,0.0265,1.3738,2.0279,0.5072,0.0900,2.3167,1.0330,0.3265
0,EURUSD,A2C(LSTM),0.8032,0.4673,0.2000,0.8320,0.0234,0.7492,1.5868,0.1293,0.1676
5,EURUSD,DQN(GRU),1.6459,0.6393,0.1999,0.5529,0.7506,0.3341,0.1706,0.7323,0.7832
1,EURUSD,DQN(LSTM),1.6684,0.0745,0.7722,1.4546,0.7357,0.0724,0.4106,0.9303,0.7827
4,EURUSD,PPO(GRU),1.0300,0.4464,0.3132,0.4705,0.0497,0.6718,1.7862,0.7682,0.7357
3,EURUSD,PPO(LSTM),2.1303,0.0650,1.8577,1.0921,1.7778,0.3349,1.1008,1.4624,0.9643
8,GBPUSD,A2C(GRU),2.1780,1.6370,1.4175,0.4330,0.5059,0.7968,2.0379,4.3362,2.3064
6,GBPUSD,A2C(LSTM),1.9161,0.4882,0.3005,0.9071,0.8240,0.8415,1.8900,0.1101,0.7725
11,GBPUSD,DQN(GRU),0.5210,0.5979,0.1257,1.3507,0.8789,0.1181,1.5125,0.1409,0.6192
7,GBPUSD,DQN(LSTM),1.6747,0.9748,1.0749,1.5444,0.1330,0.2681,1.9946,0.5814,0.5369
10,GBPUSD,PPO(GRU),0.9585,1.0271,0.3954,0.5550,0.6460,0.2701,1.3229,0.8619,0.0268
9,GBPUSD,PPO(LSTM),0.5265,1.4302,0.7262,1.6262,0.6353,0.3767,1.8169,4.5442,4.4434
14,USDCAD,A2C(GRU),0.2603,1.2020,0.9429,1.1206,0.8174,0.2492,4.8778,4.2379,1.3748
12,USDCAD,A2C(LSTM),1.9721,0.2306,0.6233,0.6047,0.8942,0.6441,0.4248,0.4635,1.1483
17,USDCAD,DQN(GRU),0.4092,0.8271,0.5032,0.2861,0.1840,0.9332,2.0135,1.1205,1.0442
13,USDCAD,DQN(LSTM),1.9932,0.0759,0.3231,0.5852,0.1935,0.0564,0.3860,0.0307,0.6273
16,USDCAD,PPO(GRU),0.4764,0.2652,0.5806,0.4430,0.1851,0.5068,1.7793,0.5252,0.2353
15,USDCAD,PPO(LSTM),1.6769,1.1604,0.8418,1.2857,0.9874,1.3244,3.9215,4.4944,3.6867

In [28]:
data.to_csv("full_result_mse.csv", index=False)