In [22]:
import pandas as pd
data=pd.read_csv('wsm5_mse.csv')
# Splitting the 'Ticket' column into two parts
data['Ticket Code'] = data['Ticket'].str.extract(r'([A-Za-z]+)')
data['Period Time'] = data['Ticket'].str.extract(r'(\d+)')

# Convert 'Period Time' to integer
data['Period Time'] = data['Period Time'].astype(int)

# Display the updated dataframe
# Removing the numeric part (1440) from the 'Ticket' column
data['Ticket'] = data['Ticket Code']
data['Weighted Score m5'] = data['Weighted Score']

# Sorting the dataframe by 'Ticket' and then by 'Model'
data= data[['Ticket', 'Model', 'Weighted Score m5']]
sorted_data1 = data.sort_values(by=['Ticket', 'Model'])
# Display the sorted dataframe
sorted_data1.head()

    Ticket      Model  Weighted Score m5
16  EURUSD   A2C(GRU)            -0.0184
1   EURUSD  A2C(LSTM)             0.5310
6   EURUSD   DQN(GRU)             0.4551
3   EURUSD  DQN(LSTM)             0.4795
10  EURUSD   PPO(GRU)             0.3671

In [21]:
import pandas as pd
data=pd.read_csv('wsh1_mse.csv')

# Splitting the 'Ticket' column into two parts
data['Ticket Code'] = data['Ticket'].str.extract(r'([A-Za-z]+)')
data['Period Time'] = data['Ticket'].str.extract(r'(\d+)')

# Convert 'Period Time' to integer
data['Period Time'] = data['Period Time'].astype(int)

# Display the updated dataframe
# Removing the numeric part (1440) from the 'Ticket' column
data['Ticket'] = data['Ticket Code']
data['Weighted Score H1'] = data['Weighted Score']

# Sorting the dataframe by 'Ticket' and then by 'Model'
data= data[['Ticket', 'Model', 'Weighted Score H1']]
sorted_data2 = data.sort_values(by=['Ticket', 'Model'])
# Display the sorted dataframe
sorted_data2.head()

    Ticket      Model  Weighted Score H1
15  EURUSD   A2C(GRU)           0.109898
8   EURUSD  A2C(LSTM)           0.389555
0   EURUSD   DQN(GRU)           0.438052
9   EURUSD  DQN(LSTM)           0.368668
11  EURUSD   PPO(GRU)           0.318731

In [20]:
import pandas as pd
data=pd.read_csv('wsh1_mse copy.csv')
# Splitting the 'Ticket' column into two parts
data['Ticket Code'] = data['Ticket'].str.extract(r'([A-Za-z]+)')
data['Period Time'] = data['Ticket'].str.extract(r'(\d+)')

# Convert 'Period Time' to integer
data['Period Time'] = data['Period Time'].astype(int)

# Display the updated dataframe
# Removing the numeric part (1440) from the 'Ticket' column
# Display the updated dataframe
# Removing the numeric part (1440) from the 'Ticket' column
data['Ticket'] = data['Ticket Code']
data['Weighted Score D1'] = data['Weighted Score']

# Sorting the dataframe by 'Ticket' and then by 'Model'
data= data[['Ticket', 'Model', 'Weighted Score D1']]
sorted_data3 = data.sort_values(by=['Ticket', 'Model'])
# Display the sorted dataframe
sorted_data3.head()

    Ticket      Model  Weighted Score D1
14  EURUSD   A2C(GRU)             0.1730
2   EURUSD  A2C(LSTM)             0.3699
9   EURUSD   DQN(GRU)             0.3260
3   EURUSD  DQN(LSTM)             0.3692
1   EURUSD   PPO(GRU)             0.3715

In [24]:
data=sorted_data1

In [26]:
data['Weighted Score D1'] = sorted_data3['Weighted Score D1']
data['Weighted Score H1'] = sorted_data2['Weighted Score H1']

In [28]:
data.to_csv("full_result.csv", index=False)