In [1]:
import pandas as pd
df= pd.read_csv("EURUSD1440_data.csv")

In [4]:
df[['datadate','tic','adjcp','adjcp','high','low','volume']]

          datadate         tic    adjcp    adjcp     high      low  volume
0     200711270000  EURUSD1440  1.48710  1.48710  1.48061  1.48332  844109
1     200711280000  EURUSD1440  1.48337  1.48337  1.47078  1.48372  857946
2     200711290000  EURUSD1440  1.48368  1.48368  1.47188  1.47561  861008
3     200711300000  EURUSD1440  1.47552  1.47552  1.46231  1.46313  840560
4     200712020000  EURUSD1440  1.46360  1.46360  1.46338  1.46583   21026
...            ...         ...      ...      ...      ...      ...     ...
4998  202311290000  EURUSD1440  1.10041  1.10041  1.09601  1.09732  263728
4999  202311300000  EURUSD1440  1.09731  1.09731  1.08794  1.08916  339794
5000  202312010000  EURUSD1440  1.08917  1.08917  1.08287  1.08788  340570
5001  202312030000  EURUSD1440  1.08771  1.08771  1.08766  1.08857   14945
5002  202312040000  EURUSD1440  1.08858  1.08858  1.08665  1.08801   42776

[5003 rows x 7 columns]